### ISSUE TITLE
Test the current state of the app

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trolley-tracker-agent#1]
The app has been stripped of all related SciWiNet code and successfully compiles and loads on an emulator. It needs to be tested on a device to see if it still receives location updates correctly.

**Comment by jeremywight** [comment]
Awesome! So I can compile this using the Android SDK and test the debug.apk file on my device?

**Comment by ajhodges** [comment]
Yep! Theoretically. However you won't see any output without an application that can view logcat. I'm planning on testing this today, so I'll also push new code that has more interesting output that you can test.

**Comment by jeremywight** [comment]
Awesome. Thanks Adam

**Comment by ajhodges** [comment]
The app collects location pretty well for the most part. There are a couple kinks with reliability that will have to be worked out before it's 'trolley ready'. Mainly with making sure the service is started when the phone runs and doesn't shut off if the phone goes in a low power state or something.

**Comment by jeremywight** [comment]
Are we ready for a possible permanent device then?

**Comment by ajhodges** [comment]
We can certainly start shopping around!

**Comment by jeremywight** [comment]
Do you expect we will need to root it? There is a Galaxy S3 on Craigslist
right now for $120 that will work with my T-Mobile plan, however Samsung's
are a pain to root.

**Comment by ajhodges** [comment]
Depends on how fancy we want to get with it (with a rooted phone we could do something fancy like make it turn on and off when the trolley is/isn't running). I think a rootable phone is a good option to go with. I personally have had bad experiences with older samsung GPS's, too.

I recommend taking a look at the Moto E's, which have more recent hardware than the S3 and can be had brand new for ~$100 or used for ~$60 (there are two generations, the 2nd gen might be a touch pricer but is more recent). If we got the GSM version it will work on both T-Mobile and AT&T.
