### ISSUE TITLE
Update to new API

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker-agent#10]
(If not already done)  Post location to new API **_POST /api/v1/Trolleys/:Number/Location**_  .   Right now there is a separate definition for backward compatibility, but it will help future maintenance to use only the new API for consistency with the rest of the API conventions.  

API is not case sensitive.

**Comment by ajhodges** [comment]
Thanks for the heads up, I didn't know about the new endpoint. I will let you know once it's changed over!
